name: (Release) Build and Push Single image to Production

on: 
  workflow_dispatch:
  push:
    branches:
      - svk

env:
  VERSION: latest

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        model: [arcface-r100-gpu, mobilenet-gpu]
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2
      - name: Set tags from git output
        id: tag_vars
        run: |
          echo "tag=${{ github.ref_name }}-$(git rev-parse HEAD | cut -c 1-7 | tr -d '\n')" >> $GITHUB_OUTPUT
          echo "tag_latest=${{ github.ref_name }}-latest" >> $GITHUB_OUTPUT
          echo "ref_name=${{ github.ref_name }}" >> $GITHUB_OUTPUT
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
            registry: ghcr.io
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./custom-builds/Single-Docker-File/
          push: true
          platforms: linux/amd64
          build-args: |
            BASE_IMAGE=ghcr.io/${{ github.actor }}/compreface-core:${VERSION}-${{ matrix.model }}
            VERSION=${VERSION}
          tags: |
            ghcr.io/${{ github.actor }}/compreface:${VERSION}-${{ matrix.model }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max