name: (Release) Build and Push Custom builds

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version (e.g., 1.0.0)
        required: true
  push:
    branches:
      - svk

env:
  REGISTRY: ghcr.io
  DOCKER_REGISTRY: ghcr.io/${{ github.actor }}/
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Check Out Repo
       uses: actions/checkout@v2
     - name: Build images
       env:
         VERSION: ${{ github.event.inputs.version }}
       working-directory: ./embedding-calculator/
       run: |
         make build-images-gpu
         docker images
     - name: Login to Docker Hub
       uses: docker/login-action@v2
       with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
     - name: Push images to Docker Hub
       working-directory: ./embedding-calculator/
       run: |
         docker push --all-tags ${DOCKER_REGISTRY}compreface-core-base
         docker push --all-tags ${DOCKER_REGISTRY}compreface-core
         

