name: (Release) Build and Push Single image to Production

on: 
  workflow_dispatch:
  push:
    branches:
      - svk

env:
  VERSION: svk
  REGISTRY: ghcr.io
  DOCKER_REGISTRY: ghcr.io/${{ github.actor }}/

jobs:
  build-custom:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - name: Set tags from git output
        id: tag_vars
        run: |
          echo "tag=${{ github.ref_name }}-$(git rev-parse HEAD | cut -c 1-7 | tr -d '\n')" >> $GITHUB_OUTPUT
          echo "tag_latest=${{ github.ref_name }}-latest" >> $GITHUB_OUTPUT
          echo "ref_name=${{ github.ref_name }}" >> $GITHUB_OUTPUT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
          version: latest
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v2
      - name: Login to Docker 
        uses: docker/login-action@v2
        with:
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
            registry: ghcr.io
      - name: Build images
        env:
          VERSION: ${{ steps.tag_vars.outputs.ref_name }}
        working-directory: ./embedding-calculator/
        run: |
          make build-images-gpu
          docker images

  build:
    needs: build-custom
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        model: [arcface-r100-gpu, mobilenet-gpu]
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2
      - name: Set tags from git output
        id: tag_vars
        run: |
          echo "tag=${{ github.ref_name }}-$(git rev-parse HEAD | cut -c 1-7 | tr -d '\n')" >> $GITHUB_OUTPUT
          echo "tag_latest=${{ github.ref_name }}-latest" >> $GITHUB_OUTPUT
          echo "ref_name=${{ github.ref_name }}" >> $GITHUB_OUTPUT
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
            registry: ghcr.io
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./custom-builds/Single-Docker-File/Dockerfile
          push: true
          platforms: linux/amd64
          build-args: |
            BASE_IMAGE=ghcr.io/${{ github.actor }}/compreface-core:${{ env.VERSION }}-${{ matrix.model }}
          tags: |
            ${{ env.DOCKER_REGISTRY }}compreface:${{ env.VERSION }}-${{ matrix.model }}
          cache-from: type=gha
          cache-to: type=gha,mode=max