name: (Release) Build and Push Single image to Production

on: 
  workflow_dispatch:
  push:
    branches:
      - svk

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2
      - name: Set tags from git output
        id: tag_vars
        run: |
          echo "tag=${{ github.ref_name }}-$(git rev-parse HEAD | cut -c 1-7 | tr -d '\n')" >> $GITHUB_OUTPUT
          echo "tag_latest=${{ github.ref_name }}-latest" >> $GITHUB_OUTPUT
          echo "ref_name=${{ github.ref_name }}" >> $GITHUB_OUTPUT
      - name: Build images
        env:
          VERSION: latest
        working-directory: ./custom-builds/Single-Docker-File/
        run: |
          docker build -f Dockerfile --build-arg BASE_IMAGE=${{ github.actor }}/compreface-core:${VERSION}                  --build-arg VERSION=${VERSION} -t ${{ github.actor }}/compreface:latest ./../..
          docker build -f Dockerfile --build-arg BASE_IMAGE=${{ github.actor }}/compreface-core:${VERSION}                  --build-arg VERSION=${VERSION} -t ${{ github.actor }}/compreface:${VERSION} ./../..
          docker build -f Dockerfile --build-arg BASE_IMAGE=${{ github.actor }}/compreface-core:${VERSION}-facenet          --build-arg VERSION=${VERSION} -t ${{ github.actor }}/compreface:${VERSION}-facenet ./../..
          docker build -f Dockerfile --build-arg BASE_IMAGE=${{ github.actor }}/compreface-core:${VERSION}-arcface-r100     --build-arg VERSION=${VERSION} -t ${{ github.actor }}/compreface:${VERSION}-arcface-r100 ./../..
          docker build -f Dockerfile --build-arg BASE_IMAGE=${{ github.actor }}/compreface-core:${VERSION}-arcface-r100-gpu --build-arg VERSION=${VERSION} -t ${{ github.actor }}/compreface:${VERSION}-arcface-r100-gpu ./../..
          docker build -f Dockerfile --build-arg BASE_IMAGE=${{ github.actor }}/compreface-core:${VERSION}-mobilenet        --build-arg VERSION=${VERSION} -t ${{ github.actor }}/compreface:${VERSION}-mobilenet ./../..
          docker build -f Dockerfile --build-arg BASE_IMAGE=${{ github.actor }}/compreface-core:${VERSION}-mobilenet-gpu    --build-arg VERSION=${VERSION} -t ${{ github.actor }}/compreface:${VERSION}-mobilenet-gpu ./../..
          docker images 
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
            registry: ghcr.io
      - name: Push images to Docker Hub
        working-directory: ./custom-builds/Single-Docker-File/
        run: |
          docker push --all-tags ${{ github.actor }}/compreface

